site_name: 得力云开放文档中心
site_url: http://docs.delicloud.com
site_author: 徐超国


pages:
    - 首页: index.md
    - 标准接入协议: 
      - 设备标准接入协议: general/device/index.md
      - 应用标准接入协议: general/app/index.md
      - JSSDK API接口说明: general/jssdk/index.md
    - 业务场景接入协议:
      - 云考勤接入协议:  business/KQ/index.md
      - 智能会议笔接入协议: business/PPT/index.md